thistuple = ("apple", "banana", "cherry", "apple", "cherry")
print(thistuple)
tup=(7,2,4,5,6,7,2,4,5)
print(tup)
my_tuple = (1, 2, 2, 3, "apple", "apple")
print(my_tuple)
my_tuple = ("apple", "banana", "cherry","Banana","Cherry")
print(my_tuple)
print(my_tuple[0])   
print(my_tuple[1])   
print(my_tuple[2]) 
print(my_tuple[3])