#Checking type()
mytuple=('Sathvika','Bunny','Lucky','Vinay','Teja')
print(type(mytuple))
tuple=(4,5,6,32,6)
print(type(tuple))
tuple=(23.4,54.6,87.5,56.3)
print(type(tuple))
tuple=(True,False,True,False)
print(type(tuple))

