#Range of Indexes(You can specify a range of indexes by specifying where to start and where to end the range.When specifying a range, the return value will be a new tuple with the specified items.)
thistuple=('Zee','Maa','Maa Movies','Gemini','Zee Cinema')
print(thistuple[:1])
print(thistuple[:2])
print(thistuple[:3])
print(thistuple[:4])
print(thistuple[:5])
print(thistuple[2:5])
print(thistuple[1:3])
print(thistuple[1:])
print(thistuple[2:])
print(thistuple[3:])
print(thistuple[4:])
print(thistuple[5:])